### ISSUE TITLE
4.0RC1 Meeting notes - 18 April 2022

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2499]
Agenda:

# Must haves for RC1

- [x] plugin activation/deactivation final decision and assignment, must-have for RC1 -> A decision is made to remove the chain since it's not needed. @lifeforms added an example variable in dummy-config. @dune73 will review and update the dummy-plugin, and will also gather information to documenting the dis/enablement in virtualhosts. @theseion will help with updating the plugins.
- [x] look through issues assigned for 4.0 https://github.com/coreruleset/coreruleset/milestone/10
- [x] #2498 @RedXanadu has offered to merge the old docs page, @lifeforms will take care of the menu and the redirects.
- [x] Different docs for different CRS versions. Opinions differ on this. Will be discussed later.
- [x] The [plugin-registry](https://github.com/coreruleset/plugin-registry) is complete? Yes. Merged.

# Todo after RC1

- [ ] #2452 Fill the 'type' in the plugin registry ('exclusion', 'official; research') and a stability field ('draft', 'production'). Duplicate the info in a YAML file for automatic usage?
- [ ] #2443 After RC1 but before 9 May when @dune73 needs it for a presentation on CRS4.
- [x] #2379 can be polished after RC1 - @lifeforms tested successfully
- [ ] #2394 can be polished after RC1 - @lifeforms tested on new phpMyAdmin version after RC1 - test was partially a failure, does anyone else have a new phpMyAdmin install to test, @azurit ?
- [x] For other plugins, we don't really have the infrastructure and time to set up instances of every app. We will rely on bug reports and frequent releases.
- [ ] #2500 - bring back GeoIP reputation plugin
- [ ] #2501 - bring back RBL reputation plugin
- [x] Put a notice in crs-setup.conf.example where the exclusions were. Put links to find the plugins and tell about their automatic activation, unless you disable them. @lifeforms
- [ ] is #2417 running well on coraza? Compability is a must have for our final release. @jptosso will test
