### ISSUE TITLE
Rework INSTALL to make it v4 friendly

### ISSUE THREAD

**Issue by fzipi** [coreruleset/coreruleset#2826]
### Describe the bug

Right now the [INSTALL file](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/INSTALL) mentions CRS v3 and how to upgrade from v2.

**Requirements**:
- [x] update where says CRS 3 to CRS 4
- [x] mention compatible engines (like Coraza)
- [x] add a section `Upgrading from CRS 3.x`
- [x] probably get in sync with https://coreruleset.org/docs/deployment/install/ ?
- [x] move to markdown?

**Comment by RedXanadu** [comment]
It would definitely make sense to synchronise the `INSTALL` file with what we have on the documentation site. There's no point in maintaining two separate install guides.

We also have engine and integration documentation, so if we want to cover engines (like Coraza) then the `INSTALL` file could become simply a concatenation of the "engines" page plus the "install" page(s) from the documentation website.

**Comment by fzipi** [comment]
@RedXanadu Can you take the lead on this one?

**Comment by RedXanadu** [comment]
I can, but it's low on my list of things to do. This will be a time consuming and not very fun task.

I can look at this sometime next year.

**Comment by fzipi** [comment]
Done. Check linked PR.

**Comment by RedXanadu** [comment]
I agree with @lifeforms . The key is making sure nothing is missed, i.e. all of the information, tips, wisdom etc. from the current INSTALL file must be retained. So, anything that is missing must be added to the "new" install guide, whether that's in the CRS repo or on our website.

That is the time consuming part: reading both sources of information and then reconciling them. But it must be done, otherwise we will potentially be throwing away years of knowledge.

**Comment by RedXanadu** [comment]
Okay: my current proposal:

---

We currently have _four_ different install guides:

- [`INSTALL`](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/INSTALL)
- [Quick Start Guide](https://coreruleset.org/docs/deployment/quick_start/)
- [Extended Install](https://coreruleset.org/docs/deployment/install/)
- [coreruleset.org/installation/](https://coreruleset.org/installation/)

_We should not maintain four separate guides:_

- **It's bad for us:** lots of work to maintain, and realistically we simply won't maintain them all (which is the current situation).
- **It's bad for users:** it's confusing - where to start? Which guide should a user read? Which ones are relevant and up to date?

We should squash them into a single source of truth for install documentation.

## Plan

- Remove https://coreruleset.org/installation/ but move any _unique content_ out of there and into coreruleset.org/docs (/installation/ then becomes a 301 redirect to the new /docs install page).
- Move around the content from the two install pages on coreruleset.org/docs:
  [Quick Start Guide](https://coreruleset.org/docs/deployment/quick_start/) and [Extended Install](https://coreruleset.org/docs/deployment/install/) become something like:
  "Install: Compatible WAF Engine" and "Install: The Core Rule Set"
  which seems like a more logical split of the content and instructions we currently have.
- The [`INSTALL`](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/INSTALL) document explicitly states it does not contain engine-related instructions. So, `INSTALL` becomes a plain text copy of the new "Install: The Core Rule Set" file on /docs.

---

## TODO

- [ ] r

**Comment by dune73** [comment]
Good plan. Thank you @RedXanadu.

**Comment by theseion** [comment]
+100 on your proposal! Thanks!

**Comment by fzipi** [comment]
@RedXanadu @dune73 Will this need work before v4?

**Comment by fzipi** [comment]
From what I understand, we need to `The [INSTALL](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/INSTALL) document explicitly states it does not contain engine-related instructions. So, INSTALL becomes a plain text copy of the new "Install: The Core Rule Set" file on /docs.`

**Comment by dune73** [comment]
Not on top of things here. I'll have to defer to @RedXanadu.

**Comment by fzipi** [comment]
I think that what you want on `Install: The Core Rule Set` is basically... the quick_start.md.

So I'm pushing this file now as the new INSTALL.md

**Comment by fzipi** [comment]
@dune73 Can we remove the `coreruleset.org/installation` and redirect to the `coreruleset.org/docs/deployment/install` instead?

**Comment by dune73** [comment]
I'm fine with that. I would probably keep the redirect, but remove it from the top menu. It's obvious where the installation will be documented and even if it's attractive to have a direct link, I think the complexity of the software forces you to invest more than a 2min quick installation to get it running properly.

**Comment by fzipi** [comment]
Ok, redirected that url to the docs, and removed it from the menu. Closing this one.
