### ISSUE TITLE
Create status page-specific tests

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#2953]
### Motivation

For the Status Page project, we require at least one test for each rule that triggers that rule **and no other rules**.

For many rules, _all_ of the existing tests trigger multiple rules. New rules need to be devised for these situations.

### Additional context

For full context, read about the Status Page project:

https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage
https://github.com/coreruleset/status-page

### Progress tracker

- [x] 920100 NOK (only tests hitting additional rules; test 920100-10 has only 2.) #2952
- [ ] 920160 NOK (no suitable log_contains test)
- [ ] 920181 NOK (no suitable log_contains test)
- [x] 920190 NOK (only tests hitting additional rules; test 920190-2 has only 2) #2956
- [x] 920250 NOK (only tests hitting additional rules; test 920250-1 has only 1) #2971
- [ ] 920260 NOK (only tests hitting additional rules; test 920260-1 has only 1) :exclamation: Impossible? Cannot trigger 920260 with a Microsoft Unicode character like `%uFF48` without triggering one of the PL 1 rules that detect encoding abuse (detecting the presence of a `%` and then performing `validateUrlEncoding` which will fail on this weird `%u…` encoding.)
- [ ] 920290 NOK (no suitable log_contains test)
- [ ] 920310 NOK (only tests hitting additional rules; test 920310-1 has only 1) :exclamation: Impossible? Cannot trigger this rule, which requires an empty Accept header, without also triggering PL 1 rule 920600, which requires having an Accept header containing a valid `charset` parameter (which an empty header cannot have).
- [ ] 920311 NOK (only tests hitting additional rules; test 920311-1 has only 1) :exclamation: Impossible? Cannot trigger this rule, which requires an empty Accept header, without also triggering PL 1 rule 920600, which requires having an Accept header containing a valid `charset` parameter (which an empty header cannot have).
- [x] 920340 NOK (only tests hitting additional rules; test 920340-1 has only 1) #2972
- [ ] 920360 NOK (only tests hitting additional rules; test 920360-1 has only 1) :question: Untestable? Optional rule that is off by default: _Block request if the length of any argument name is too high. Default: unlimited_
- [ ] 920370 NOK (only tests hitting additional rules; test 920370-1 has only 1) :question: Untestable? Optional rule that is off by default: _Block request if the length of any argument value is too high. Default: unlimited_
- [ ] 920380 NOK (only tests hitting additional rules; test 920380-1 has only 1) :question: Untestable? Optional rule that is off by default: _Block request if number of arguments is too high. Default: unlimited_
- [ ] 920390 NOK (only tests hitting additional rules; test 920390-1 has only 1)  :question: Untestable? Optional rule that is off by default: _Block request if the length of any argument value is too high. Default: unlimited_
- [ ] 920400 NOK (no suitable log_contains test) :question: Untestable? Optional rule that is off by default: _Block request if the file size of any individual uploaded file is too high. Default: unlimited_
- [ ] 920410 NOK (ftw error) :question: Untestable? Optional rule that is off by default: _Block request if the total size of all combined uploaded files is too high. Default: unlimited_
- [x] 920470 NOK (only tests hitting additional rules; test 920470-1 has only 1) #3058 
- [ ] 920610 NOK (no suitable log_contains test) :exclamation: Impossible? Cannot trigger this rule which is looking for a raw, unencoded fragment "#" in the request URI: this will always cause Apache to return a '400 Bad Request'.
- [ ] 921110 NOK (only tests hitting additional rules; test 921110-1 has only 1) :exclamation: Impossible? Cannot trigger this rule, which requires a match of `\s+http/\d`, without also triggering PL 1 rule 921130 which matches against `\bhttp/\d`.
- [x] 921120 NOK (only tests hitting additional rules; test 921120-1 has only 1) #3083
- [ ] 921140 NOK (no suitable log_contains test)
- [x] 921150 NOK (only tests hitting additional rules; test 921150-1 has only 1) #3158
- [ ] 921421 NOK (only tests hitting additional rules; test 921421-1 has only 1)
- [ ] 922120 NOK (only tests hitting additional rules; test 922120-1 has only 1)
- [ ] 930100 NOK (only tests hitting additional rules; test 930100-1 has only 1)
- [ ] 932160 NOK (only tests hitting additional rules; test 932160-1 has only 1)
- [ ] 932175 NOK (only tests hitting additional rules; test 932175-1 has only 1)
- [ ] 932180 NOK (ftw error)
- [ ] 932240 NOK (ftw error)
- [ ] 934150 NOK (only tests hitting additional rules; test 934150-1 has only 1)
- [ ] 941130 NOK (only tests hitting additional rules; test 941130-1 has only 1)
- [x] 941140 NOK (only tests hitting additional rules; test 941140-3 has only 4) #2995
- [x] 941170 NOK (only tests hitting additional rules; test 941170-3 has only 1) #2994
- [ ] 941190 NOK (only tests hitting additional rules; test 941190-4 has only 2) :exclamation: Impossible: Minimal string of 941190 `<styletest>@i` will always also match rule 941160 and libinjection rule 941100 
- [x] 941200 NOK (only tests hitting additional rules; test 941200-3 has only 1) #2993
- [ ] 941230 NOK (only tests hitting additional rules; test 941230-1 has only 2) :exclamation: Impossible: Minimal string of 941230 `<embed src=` will always also match rule 941160 and libinjection rule 941100 
- [x] 941240 NOK (only tests hitting additional rules; test 941240-1 has only 2) #2975
- [ ] 941250 NOK (only tests hitting additional rules; test 941250-1 has only 3) :exclamation: Impossible: Minimal string of 941250 `<meta http-equiv=` will always also match rule 921130, 941160 and libinjection rule 941100 
- [ ] 941260 NOK (only tests hitting additional rules; test 941260-1 has only 3) :exclamation: Impossible: Minimal string of 941260 `<meta+charset=` will always also match rule 921130, 941160 and libinjection rule 941100 
- [ ] 941270 NOK (only tests hitting additional rules; test 941270-1 has only 2) :exclamation: Impossible: First part of 941270 `<link+` will always also match rule 941160 and libinjection rule 941100
- [ ] 941280 NOK (only tests hitting additional rules; test 941280-1 has only 2) :exclamation: Impossible: First part of 941280 `<base+` will always also match rule 941160 and libinjection rule 941100
- [ ] 941290 NOK (only tests hitting additional rules; test 941290-1 has only 2) :exclamation: Impossible: Minimal string of 941290 `<applet/` will always also match rule 941160 and libinjection rule 941100
- [ ] 941300 NOK (only tests hitting additional rules; test 941300-1 has only 2) :exclamation: Impossible: First part of 941300 `<OBJECT/` will always also match rule 941160 and libinjection rule 941100
- [x] 941310 NOK (only tests hitting additional rules; test 941310-1 has only 1) #2974
- [x] 941400 NOK (only tests hitting additional rules; test 941400-1 has only 1) #2969
- [x] 942170 NOK (only tests hitting additional rules; test 942170-2 has only 2) #2968
- [x] 942270 NOK (only tests hitting additional rules; test 942270-1 has only 1) #2967
- [x] 942350 NOK (only tests hitting additional rules; test 942350-1 has only 1) #2965 
- [x] 942500 NOK (only tests hitting additional rules; test 942500-1 has only 1) #2964 
- [x] 943100 NOK (only tests hitting additional rules; test 943100-1 has only 5) #2962
- [ ] 944100 NOK (only tests hitting additional rules; test 944100-1 has only 2) :exclamation: Impossible: The minimal string `uri: "/?arg=java.lang.Runtime"` will always also match rule 944110 and 944130.

**Comment by dune73** [comment]
2nd iteration of this issue. We have 80% coverage, so I think we can close this now.
